In [3]:
import datetime 
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import db_dtypes
import pymssql
from shutil import copyfile
from openpyxl import load_workbook
import os
from google.cloud import bigquery
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '../../../BQ.json'

DB_info = {'server':'192.168.61.119:7622', 'user':'BAReporting', 'password':'KeHeCReme8he'}

client = bigquery.Client()

In [ ]:
# LMS UU by Search
# No. of Keyword Search Landmark = No. of Search Tips Landmark + No. of Advance Search Landmark = quick + adv
# No. of Search Tips Landmark (quick)

sql = r"""
with temp as 
    (select deviceid,lower(eventlabel) as screen,
     lower(LAG(eventlabel) OVER(ORDER BY sessionid, time)) AS prev_screen
     from `openrice-production.ORGA.SV_202609*`
     where lower(eventlabel) like  'hk.lms2.%.tab.-%' or lower(eventlabel) =  'hk.qcksearch' or lower(eventlabel) like  'hk.advsearch' )

  
select sum(case when prev_screen = 'hk.qcksearch' then 1 end) as quick_,
sum(case when prev_screen = 'hk.advsearch' then 1 end ) as adv_,
count(distinct deviceid) as uu,screen from temp
where (screen = 'hk.lms2.42.tab.-990.1'
or screen = 'hk.lms2.65.tab.-990.1'
or screen = 'hk.lms2.35215.tab.-990.1'
or screen = 'hk.lms2.35329.tab.-990.1')
and prev_screen like '%search%'
group by screen
order by 2 desc

"""

In [ ]:
df = client.query(sql).to_dataframe()
df

C:\Users\lenalee\AppData\Roaming\Python\Python313\site-packages\google\cloud\bigquery\table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

   quick_  adv_     uu                    screen
0   21813  1668  18071     hk.lms2.42.tab.-990.1
1   21712  1587  19676     hk.lms2.65.tab.-990.1
2   14034  1124  11951  hk.lms2.35329.tab.-990.1
3   10704   582  10313  hk.lms2.35215.tab.-990.1

In [ ]:
# LMS PV by App Index Icon (ios, android)  --> http://172.17.2.220:8888/notebooks/Tom/report/20260707/gen.ipynb
# LMS UU by Index Icon (ios, android)

sql_1 = r"""
WITH base AS (
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260901`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260902`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260903`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260904`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260905`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260906`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260907`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260908`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260909`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260910`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260911`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260912`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260913`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260914`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260915`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260916`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260917`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260918`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260919`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260920`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260921`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260922`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260923`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260924`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260925`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260926`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260927`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260928`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260929`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
UNION ALL
SELECT
      REGEXP_EXTRACT(LOWER(eventlabelraw), r'lndid:([^;]+)') AS lndid,
      LOWER(platform) AS platform,
      deviceid
    FROM `openrice-production.ORGA.PV_20260930`
    WHERE LOWER(EventAction) = 'or.search.quick'
      AND LOWER(eventlabelraw) LIKE '%lndid:%'
      AND LOWER(platform) IN ('ios','android')
      AND LOWER(eventlabelraw) LIKE '%page:1%'
      AND LOWER(eventlabelraw) LIKE '%sn:hk.home%'
)
SELECT
  lndid,
  platform,
  COUNT(1) AS event_count,
  COUNT(DISTINCT deviceid) AS device_count
FROM base
WHERE lndid IN ('42','65','35215','35329')
GROUP BY lndid, platform
ORDER BY event_count DESC

"""

In [ ]:
df_1 = client.query(sql_1).to_dataframe()
df_1

C:\Users\lenalee\AppData\Roaming\Python\Python313\site-packages\google\cloud\bigquery\table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

   lndid platform  event_count  device_count
0     65  android         1163           831
1     42  android         1137           762
2  35329  android          564           436
3  35215  android          481           393
4     42      ios          260           202
5     65      ios          254           194
6  35329      ios          170           133
7  35215      ios          163           132

In [ ]:
# LMS Monthly PV, LMS Monthly UU -> http://172.17.2.220:8888/notebooks/Tom/report/20260707/gen.ipynb

sql_2 = r"""
WITH sv AS (
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260901`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260902`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260903`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260904`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260905`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260906`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260907`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260908`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260909`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260910`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260911`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260912`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260913`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260914`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260915`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260916`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260917`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260918`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260919`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260920`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260921`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260922`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260923`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260924`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260925`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260926`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260927`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260928`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260929`
UNION ALL
SELECT EventLabel, deviceid, platform FROM `openrice-production.ORGA.SV_20260930`
)
SELECT
    l.namelang1,
    l.namelang2,
    COUNT(1) AS pv,
    COUNT(DISTINCT deviceid) AS uu
FROM sv
LEFT JOIN `openrice-production.openrice3.landmark` l
    ON l.landmarkid = REGEXP_EXTRACT(EventLabel, r'^[^.]+\.[^.]+\.([^.]+)')
WHERE LOWER(EventLabel) LIKE 'hk.lms2.%'
  AND LOWER(EventLabel) LIKE '%-%'
  AND LOWER(platform) IN ('ios')
GROUP BY
    l.namelang1,
    l.namelang2
ORDER BY pv DESC
"""

In [ ]:
df_2 = client.query(sql_2).to_dataframe()

C:\Users\lenalee\AppData\Roaming\Python\Python313\site-packages\google\cloud\bigquery\table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        namelang1        namelang2     pv     uu
0           屯門市廣場         tmtplaza  85413  14949
1            荃新天地         Citywalk  56765  16271
2             奧海城    Olympian City  53640   9806
3            淘大商場       Amoy Plaza  44131  11766
4    Fashion Walk     Fashion Walk  36282  19786
..            ...              ...    ...    ...
200          天星碼頭  Star Ferry Pier      2      2
201         _0099            _0099      1      1
202         新世界大廈  New World Tower      1      1
203        莊士倫敦廣場     London Plaza      1      1
204         奧海城一期  Olympian City 1      1      1

[205 rows x 4 columns]

In [ ]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df_2

In [ ]:
# POIs Total SR2 Impressions (col W) -> http://172.17.2.220:8888/notebooks/Tom/report/20260707/gen.ipynb

sql_3 = r"""
WITH raw AS (
    
    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260901`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260902`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260903`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260904`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260905`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260906`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260907`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260908`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260909`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260910`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260911`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260912`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260913`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260914`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260915`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260916`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260917`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260918`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260919`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260920`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260921`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260922`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260923`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260924`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260925`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260926`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260927`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260928`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260929`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
UNION ALL

    SELECT time, EventLabel, deviceid
    FROM `openrice-production.ORGA.SV_20260930`
    WHERE LOWER(EventLabel) LIKE '%hk.sr2.overview%'
    
),
temp AS (
    SELECT
        EXTRACT(YEAR FROM time) AS year_,
        EXTRACT(MONTH FROM time) AS month_,
        REGEXP_EXTRACT(
            SPLIT(EventLabel, '.')[OFFSET(ARRAY_LENGTH(SPLIT(EventLabel, '.')) - 1)],
            r'\d+'
        ) AS poiid,
        deviceid,
        COUNT(1) AS count_
    FROM raw
    GROUP BY poiid, deviceid, month_, year_
)
SELECT
    year_,
    month_,
    LandmarkId,
    SUM(count_) AS total_count,
    COUNT(DISTINCT deviceid) AS distinct_device_count
FROM temp
LEFT JOIN `openrice-production.openrice3.landmarkpoi` lp
    ON lp.poiid = CAST(temp.poiid AS INT64)
WHERE LandmarkId IN (42, 35179, 35241, 35276, 65, 35215, 35329)
GROUP BY LandmarkId, month_, year_
ORDER BY year_, month_, LandmarkId
"""

In [ ]:
df_3 = client.query(sql_3).to_dataframe()

C:\Users\lenalee\AppData\Roaming\Python\Python313\site-packages\google\cloud\bigquery\table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [ ]:
df_3

   year_  month_  LandmarkId  total_count  distinct_device_count
0   2026       9          42       272160                  54070
1   2026       9          65       245447                  61043
2   2026       9       35179        48995                  14139
3   2026       9       35215        96062                  30066
4   2026       9       35241        95846                  27939
5   2026       9       35276       110735                  26469
6   2026       9       35329       216937                  47455

In [29]:
# column N-Q (Bookmark): Sino_ColN-Q.sql
# column Z-AH (POI Bookmark/Booking/Voucher/TA/VView): Sino_BizData.sql
# column XY (Total Impression, LMS): BQ: sr2 click count from LMS
# column RS (Clicks of Large/Small Banner ): BQ: LMS big banner click count
# Large Banner: hk.lms2.xxx
# Small Banner: citywalk = 65, ita = 35215, oc = 35329, tmtp = 42


# sql_4 = f"""


# """

In [30]:
# df_4 = client.query(sql_4).to_dataframe()
# df_4